/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as SancoesRouteImport } from './routes/sancoes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PortabilidadeRouteImport } from './routes/portabilidade'
import { Route as OrdensServicoRouteImport } from './routes/ordens-servico'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlosasRouteImport } from './routes/glosas'
import { Route as EstruturaRouteImport } from './routes/estrutura'
import { Route as CustosRouteImport } from './routes/custos'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as BilhetagemRouteImport } from './routes/bilhetagem'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventarioIndexRouteImport } from './routes/inventario.index'
import { Route as InventarioNovoRouteImport } from './routes/inventario.novo'
import { Route as InventarioImportarRouteImport } from './routes/inventario.importar'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SancoesRoute = SancoesRouteImport.update({
  id: '/sancoes',
  path: '/sancoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PortabilidadeRoute = PortabilidadeRouteImport.update({
  id: '/portabilidade',
  path: '/portabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensServicoRoute = OrdensServicoRouteImport.update({
  id: '/ordens-servico',
  path: '/ordens-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlosasRoute = GlosasRouteImport.update({
  id: '/glosas',
  path: '/glosas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstruturaRoute = EstruturaRouteImport.update({
  id: '/estrutura',
  path: '/estrutura',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosRoute = CustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const BilhetagemRoute = BilhetagemRouteImport.update({
  id: '/bilhetagem',
  path: '/bilhetagem',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioIndexRoute = InventarioIndexRouteImport.update({
  id: '/inventario/',
  path: '/inventario/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioNovoRoute = InventarioNovoRouteImport.update({
  id: '/inventario/novo',
  path: '/inventario/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioImportarRoute = InventarioImportarRouteImport.update({
  id: '/inventario/importar',
  path: '/inventario/importar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/bilhetagem': typeof BilhetagemRoute
  '/chamados': typeof ChamadosRoute
  '/contratos': typeof ContratosRoute
  '/custos': typeof CustosRoute
  '/estrutura': typeof EstruturaRoute
  '/glosas': typeof GlosasRoute
  '/login': typeof LoginRoute
  '/ordens-servico': typeof OrdensServicoRoute
  '/portabilidade': typeof PortabilidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/sancoes': typeof SancoesRoute
  '/usuarios': typeof UsuariosRoute
  '/whatsapp': typeof WhatsappRoute
  '/inventario/importar': typeof InventarioImportarRoute
  '/inventario/novo': typeof InventarioNovoRoute
  '/inventario/': typeof InventarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/bilhetagem': typeof BilhetagemRoute
  '/chamados': typeof ChamadosRoute
  '/contratos': typeof ContratosRoute
  '/custos': typeof CustosRoute
  '/estrutura': typeof EstruturaRoute
  '/glosas': typeof GlosasRoute
  '/login': typeof LoginRoute
  '/ordens-servico': typeof OrdensServicoRoute
  '/portabilidade': typeof PortabilidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/sancoes': typeof SancoesRoute
  '/usuarios': typeof UsuariosRoute
  '/whatsapp': typeof WhatsappRoute
  '/inventario/importar': typeof InventarioImportarRoute
  '/inventario/novo': typeof InventarioNovoRoute
  '/inventario': typeof InventarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auditoria': typeof AuditoriaRoute
  '/bilhetagem': typeof BilhetagemRoute
  '/chamados': typeof ChamadosRoute
  '/contratos': typeof ContratosRoute
  '/custos': typeof CustosRoute
  '/estrutura': typeof EstruturaRoute
  '/glosas': typeof GlosasRoute
  '/login': typeof LoginRoute
  '/ordens-servico': typeof OrdensServicoRoute
  '/portabilidade': typeof PortabilidadeRoute
  '/relatorios': typeof RelatoriosRoute
  '/sancoes': typeof SancoesRoute
  '/usuarios': typeof UsuariosRoute
  '/whatsapp': typeof WhatsappRoute
  '/inventario/importar': typeof InventarioImportarRoute
  '/inventario/novo': typeof InventarioNovoRoute
  '/inventario/': typeof InventarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auditoria'
    | '/bilhetagem'
    | '/chamados'
    | '/contratos'
    | '/custos'
    | '/estrutura'
    | '/glosas'
    | '/login'
    | '/ordens-servico'
    | '/portabilidade'
    | '/relatorios'
    | '/sancoes'
    | '/usuarios'
    | '/whatsapp'
    | '/inventario/importar'
    | '/inventario/novo'
    | '/inventario/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auditoria'
    | '/bilhetagem'
    | '/chamados'
    | '/contratos'
    | '/custos'
    | '/estrutura'
    | '/glosas'
    | '/login'
    | '/ordens-servico'
    | '/portabilidade'
    | '/relatorios'
    | '/sancoes'
    | '/usuarios'
    | '/whatsapp'
    | '/inventario/importar'
    | '/inventario/novo'
    | '/inventario'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auditoria'
    | '/bilhetagem'
    | '/chamados'
    | '/contratos'
    | '/custos'
    | '/estrutura'
    | '/glosas'
    | '/login'
    | '/ordens-servico'
    | '/portabilidade'
    | '/relatorios'
    | '/sancoes'
    | '/usuarios'
    | '/whatsapp'
    | '/inventario/importar'
    | '/inventario/novo'
    | '/inventario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditoriaRoute: typeof AuditoriaRoute
  BilhetagemRoute: typeof BilhetagemRoute
  ChamadosRoute: typeof ChamadosRoute
  ContratosRoute: typeof ContratosRoute
  CustosRoute: typeof CustosRoute
  EstruturaRoute: typeof EstruturaRoute
  GlosasRoute: typeof GlosasRoute
  LoginRoute: typeof LoginRoute
  OrdensServicoRoute: typeof OrdensServicoRoute
  PortabilidadeRoute: typeof PortabilidadeRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SancoesRoute: typeof SancoesRoute
  UsuariosRoute: typeof UsuariosRoute
  WhatsappRoute: typeof WhatsappRoute
  InventarioImportarRoute: typeof InventarioImportarRoute
  InventarioNovoRoute: typeof InventarioNovoRoute
  InventarioIndexRoute: typeof InventarioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sancoes': {
      id: '/sancoes'
      path: '/sancoes'
      fullPath: '/sancoes'
      preLoaderRoute: typeof SancoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portabilidade': {
      id: '/portabilidade'
      path: '/portabilidade'
      fullPath: '/portabilidade'
      preLoaderRoute: typeof PortabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens-servico': {
      id: '/ordens-servico'
      path: '/ordens-servico'
      fullPath: '/ordens-servico'
      preLoaderRoute: typeof OrdensServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glosas': {
      id: '/glosas'
      path: '/glosas'
      fullPath: '/glosas'
      preLoaderRoute: typeof GlosasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrutura': {
      id: '/estrutura'
      path: '/estrutura'
      fullPath: '/estrutura'
      preLoaderRoute: typeof EstruturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos': {
      id: '/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof CustosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilhetagem': {
      id: '/bilhetagem'
      path: '/bilhetagem'
      fullPath: '/bilhetagem'
      preLoaderRoute: typeof BilhetagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/': {
      id: '/inventario/'
      path: '/inventario'
      fullPath: '/inventario/'
      preLoaderRoute: typeof InventarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/novo': {
      id: '/inventario/novo'
      path: '/inventario/novo'
      fullPath: '/inventario/novo'
      preLoaderRoute: typeof InventarioNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/importar': {
      id: '/inventario/importar'
      path: '/inventario/importar'
      fullPath: '/inventario/importar'
      preLoaderRoute: typeof InventarioImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditoriaRoute: AuditoriaRoute,
  BilhetagemRoute: BilhetagemRoute,
  ChamadosRoute: ChamadosRoute,
  ContratosRoute: ContratosRoute,
  CustosRoute: CustosRoute,
  EstruturaRoute: EstruturaRoute,
  GlosasRoute: GlosasRoute,
  LoginRoute: LoginRoute,
  OrdensServicoRoute: OrdensServicoRoute,
  PortabilidadeRoute: PortabilidadeRoute,
  RelatoriosRoute: RelatoriosRoute,
  SancoesRoute: SancoesRoute,
  UsuariosRoute: UsuariosRoute,
  WhatsappRoute: WhatsappRoute,
  InventarioImportarRoute: InventarioImportarRoute,
  InventarioNovoRoute: InventarioNovoRoute,
  InventarioIndexRoute: InventarioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
